spring:
  jpa:
    show_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hospital-management-system
    username: sa
    password: