drop table if exists HOSPITAL CASCADE;
create table hospital (
  id bigint generated by default as identity,
  created_at timestamp,
  last_modified_at timestamp,
  code varchar(20) not null,
  hospital_director_name varchar(10) not null,
  name varchar(45) not null,
  primary key (id));

drop table if exists PATIENT CASCADE;
create table patient (
  id bigint generated by default as identity,
  created_at timestamp,
  last_modified_at timestamp,
  birth_day varchar(10),
  gender varchar(10) not null,
  hospital_id bigint not null,
  mobile_phone_number varchar(20),
  name varchar(45) not null,
  register_no varchar(13) not null,
  primary key (id));

drop table if exists VISIT CASCADE;
create table visit (
  id bigint generated by default as identity,
  created_at timestamp,
  last_modified_at timestamp,
  diagnosis_type varchar(255) not null,
  hospital_id bigint not null,
  reception_date_time timestamp not null,
  visit_status integer not null,
  patient_id bigint not null,
  primary key (id));
alter table visit add constraint FKrban5yeabnx30seqm69jw44e foreign key (patient_id) references patient;

SELECT * FROM HOSPITAL;
SELECT * FROM PATIENT;
SELECT * FROM VISIT;


